worker_processes 1;
events { worker_connections 1024; }

http {
  include       mime.types;
  default_type  application/octet-stream;
  sendfile      on;
  keepalive_timeout  65;

  # Rate limit (на будущее, сейчас выключено)
  # limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;

  upstream auth_upstream { server auth-svc:8000; }
  upstream task_upstream { server task-svc:8000; }
  upstream notify_upstream { server notify-svc:8000; }

  server {
    listen 80;

    # health общего шлюза
    location = /healthz { return 200 "ok\n"; }

    location /auth/ {
      proxy_pass http://auth_upstream/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_read_timeout 30s;
    }

    location /tasks/ {
      proxy_pass http://task_upstream/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_read_timeout 30s;
    }

    location /notify/ {
      proxy_pass http://notify_upstream/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_read_timeout 30s;
    }
  }
}
